### ISSUE TITLE
Create parsers for directory structure

### ISSUE THREAD

**Issue by jchmura** [APMD/PMD#1]
We need to create multiple parsers for OS specific commands and create a unified structure of files and directories.
### TODO
- [x] parser for `ls`
- [x] parser for `dir`
- [x] guess movie name

**Comment by jchmura** [comment]
Warto wykorzystać bibliotekę [guessit](http://guessit.io/).
